name: "Let me lint:fix that for you"

on: [push]

jobs:
  LMLFTFY:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out Git repository"
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: "Use Node.js 22"
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22
    - name: "Install application"
      run: |
        npm install --ignore-scripts
        cd frontend
        npm install --ignore-scripts --legacy-peer-deps
    - name: "Fix everything which can be fixed"
      run: 'npm run lint:fix'
    - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
      with:
        commit_message: "Auto-fix linting issues"
        branch: ${{ github.head_ref }}
        commit_options: '--signoff'
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
