name: "Update challenges in Companion Guide"

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'data/static/challenges.yml'

jobs:
  UpdateChallengesOnWebsite:
    if: github.repository == 'juice-shop/juice-shop'
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        token: ${{ secrets.BOT_TOKEN }}
        repository: juice-shop/pwning-juice-shop
        ref: ${{ github.ref_name }}
    - name: Update challenges.yml
      run: |
        cd docs/modules/ROOT/assets/data
        rm challenges.yml
        wget https://raw.githubusercontent.com/juice-shop/juice-shop/${{ github.ref_name }}/data/static/challenges.yml
    - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
      with:
        commit_message: "Auto-update challenges.yml from ${{ github.sha }}"
        branch: ${{ github.ref_name }}
        commit_options: '--signoff'

        # Optional commit user and author settings
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
